const types = {
	INCREMENT_LIKES: 'INCREMENT_LIKES',
	ADD_COMMENT: 'ADD_COMMENT',
	REMOVE_COMMENT: 'REMOVE_COMMENT',
	FETCH_COMMENTS: 'FETCH_COMMENTS',
	FETCH_POSTS: 'FETCH_POSTS'
};

export default types;
